AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketName:
    Type: 'String'
    Description: |
      Bucket name for uploaded PDFs.
  BucketExpirationInDays:
    Type: 'Number'
    Description: |
      Number of days after which objects in bucket are expired. Set 0 to disable.
    MinValue: 0
    Default: 7
  AccessKeySerial:
    Type: 'Number'
    Description: |
      Serial for IAM access key.
    MinValue: 1
    Default: 1

Conditions:
  GivenBucketName: !Not [!Equals [!Ref 'BucketName', '']]
  ExpireObjects: !Not [!Equals [!Ref 'BucketExpirationInDays', 0]]

Outputs:
  Bucket:
    Description: |
      Name of created S3 bucket.
    Value: !Ref 'Bucket'
  AccessKeyId:
    Description: |
      Value of AWS_ACCESS_KEY_ID.
    Value: !Ref 'AccessKey'
  SecretAccessKey:
    Description: |
      Value of AWS_SECRET_ACCESS_KEY.
    Value: !GetAtt 'AccessKey.SecretAccessKey'

Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If
        - 'GivenBucketName'
        - !Ref 'BucketName'
        - !Ref 'AWS::NoValue'
      LifecycleConfiguration:
        Rules:
          - Status: 'Enabled'
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            ExpirationInDays: !If
              - 'ExpireObjects'
              - !Ref 'BucketExpirationInDays'
              - !Ref 'AWS::NoValue'
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref 'Bucket'
      PolicyDocument: 
        Statement: 
          - Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${Bucket.Arn}/*'

  User:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: 'Upload'
          PolicyDocument:
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 's3:PutObject'
                Resource: !Sub '${Bucket.Arn}/*'
  AccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref 'User'
      Status: 'Active'
      Serial: !Ref 'AccessKeySerial'
